---
- hosts: all
  tasks:
    - name: 'Instala o PHP5'
      apt: #usa o módulo apt que atualiza caso não esteja e instala
        name: php5
        state: latest
      become: yes #executa como sudo
    - name: 'Instala o Apache2'
      apt:
        name: apache2
        state: latest
      become: yes
    - name: 'Instala o modphp'
      apt:
        name: libapache2-mod-php5
        state: latest
      become: yes