---
- hosts: database
  
  tasks:
    - name: 'Instala as dependências do SO'
      apt: #usa o módulo apt que atualiza caso não esteja e instala
        update_cache: yes
        cache_valid_time: 3600 #1h
        name:            
            - mysql-server-5.6
            - python-mysqldb          
        state: latest
      become: yes #executa como sudo
    
    - name: 'Criação do banco do MySQL'
      mysql_db:
        login_user: root
        name: wordpress_db
        state: present
        
    - name: 'Criar usuário do MySQL para o Wordpress'
      mysql_user:
        login_user: root
        name: wordpress_user
        password: 123456
        priv: 'wordpress_db.*:ALL' #format = 'db.table:priv'
        state: present

- hosts: wordpress

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: 'Instala as dependências do SO'
      apt: #usa o módulo apt que atualiza caso não esteja e instala
        update_cache: yes
        cache_valid_time: 3600 #1h
        name: 
            - php5
            - apache2
            - libapache2-mod-php5
            - php5-gd
            - libssh2-php
            - php5-mcrypt
            - php5-mysql
        state: latest
      become: yes #executa como sudo
        
    - name: 'Baixar Wordpress'
      get_url: #baixa arquivos para os hosts remotos
        url: https://wordpress.org/wordpress-5.0.tar.gz
        dest: /tmp/wordpress.tar.gz
        timeout: 420

    - name: 'Descompacta Wordpress'
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www
        remote_src: yes #está realizando a operação na máquina controlada
      become: yes #apenas o root pode mexer na pasta /var/www
    
    - name: 'Criando nosso arquivo de configurações Wordpress'
      copy:
        src: /var/www/wordpress/wp-config-sample.php
        dest: /var/www/wordpress/wp-config.php
        remote_src: yes
      become: yes
    
    - name: 'Configurando wp-config com entradas do BD'
      replace:
        path: /var/www/wordpress/wp-config.php
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      loop:
        - {regex: 'database_name_here', value: 'wordpress_db'}
        - {regex: 'username_here', value: 'wordpress_user'}
        - {regex: 'password_here', value: '123456'}
      become: yes
    
    - name: 'Configura Apache para servir Wordpress'
      copy:
        src: /vagrant/000-default.conf
        dest: /etc/apache2/sites-available/000-default.conf
        remote_src: yes
      become: yes
      notify:
        - restart apache  