---
- name: 'Baixar Wordpress'
  get_url: #baixa arquivos para os hosts remotos
    url: https://wordpress.org/wordpress-5.0.tar.gz
    dest: /tmp/wordpress.tar.gz
    timeout: 420
  tags:
    - download  

- name: 'Descompacta Wordpress'
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www
    remote_src: yes #está realizando a operação na máquina controlada
  become: yes #apenas o root pode mexer na pasta /var/www
  tags:
    - download
    
- name: 'Criando nosso arquivo de configurações Wordpress'
  copy:
    src: /var/www/wordpress/wp-config-sample.php
    dest: /var/www/wordpress/wp-config.php
    remote_src: yes
  become: yes
    
- name: 'Configurando wp-config com entradas do BD'
  replace:
    path: /var/www/wordpress/wp-config.php
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  loop:
    - {regex: 'database_name_here', value: "{{ wp_db_name }}"}
    - {regex: 'username_here', value: "{{ wp_username }}"}
    - {regex: 'password_here', value: "{{ wp_user_password }}"}
    - {regex: 'localhost', value: "{{ wp_db_ip }}"} #configura o WP com o ip do novo servidor mysql
  become: yes
    
- name: 'Configura Apache para servir Wordpress'
  template:
    src: /vagrant/ansible_files/roles/templates/000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf        
  become: yes
  notify:
    - restart apache  